export const COUNTRIES = {
    AD: { fr: 'Andorre', en: 'Andorra' },
    AE: { fr: 'Émirats Arabes Unis', en: 'United Arab Emirates' },
    AF: { fr: 'Afghanistan', en: 'Afghanistan' },
    AG: { fr: 'Antigua-Et-Barbuda', en: 'Antigua and Barbuda' },
    AI: { fr: 'Anguilla', en: 'Anguilla' },
    AL: { fr: 'Albanie', en: 'Albania' },
    AM: { fr: 'Arménie', en: 'Armenia' },
    AO: { fr: 'Angola', en: 'Angola' },
    AP: { fr: 'Région Asie/Pacifique', en: 'Asia/Pacific Region' },
    AQ: { fr: 'Antarctique', en: 'Antarctica' },
    AR: { fr: 'Argentine', en: 'Argentina' },
    AS: { fr: 'Samoa Américaines', en: 'American Samoa' },
    AT: { fr: 'Autriche', en: 'Austria' },
    AU: { fr: 'Australie', en: 'Australia' },
    AW: { fr: 'Aruba', en: 'Aruba' },
    AX: { fr: 'Îles Åland', en: 'Åland Islands' },
    AZ: { fr: 'Azerbaïdjan', en: 'Azerbaijan' },
    BA: { fr: 'Bosnie-Herzégovine', en: 'Bosnia and Herzegovina' },
    BB: { fr: 'Barbad', en: 'Barbados' },
    BD: { fr: 'Bangladesh', en: 'Bangladesh' },
    BE: { fr: 'Belgique', en: 'Belgium' },
    BF: { fr: 'Burkina Faso', en: 'Burkina Faso' },
    BG: { fr: 'Bulgarie', en: 'Bulgaria' },
    BH: { fr: 'Bahreïn', en: 'Bahrain' },
    BI: { fr: 'Burundi', en: 'Burundi' },
    BJ: { fr: 'Bénin', en: 'Benin' },
    BL: { fr: 'Saint-Barthélemy', en: 'Saint Barthélemy' },
    BM: { fr: 'Bermudes', en: 'Bermuda' },
    BN: { fr: 'Brunei Darussalam', en: 'Brunei Darussalam' },
    BO: { fr: 'État Plurinational De Bolivie', en: 'Plurinational State of Bolivia' },
    BQ: { fr: 'Bonaire, Saint-Eustache Et Saba', en: 'Bonaire, Sint Eustatius and Saba' },
    BR: { fr: 'Brésil', en: 'Brazil' },
    BS: { fr: 'Bahamas', en: 'Bahamas' },
    BT: { fr: 'Bhoutan', en: 'Bhutan' },
    BV: { fr: 'Île Bouvet', en: 'Bouvet Island' },
    BW: { fr: 'Botswana', en: 'Botswana' },
    BY: { fr: 'Biélorussie', en: 'Belarus' },
    BZ: { fr: 'Belize', en: 'Belize' },
    CA: { fr: 'Canada', en: 'Canada' },
    CC: { fr: 'Îles Cocos', en: 'Cocos Islands' },
    CD: { fr: 'République Démocratique Du Congo', en: 'Democratic Republic of the Congo' },
    CF: { fr: 'République Centrafricaine', en: 'Central African Republic' },
    CG: { fr: 'Congo', en: 'Congo' },
    CH: { fr: 'Suisse', en: 'Switzerland' },
    CI: { fr: "Côte D'Ivoire", en: "Côte d'Ivoire" },
    CK: { fr: 'Îles Cook', en: 'Cook Islands' },
    CL: { fr: 'Chili', en: 'Chile' },
    CM: { fr: 'Cameroun', en: 'Cameroon' },
    CN: { fr: 'Chine', en: 'China' },
    CO: { fr: 'Colombie', en: 'Colombia' },
    CR: { fr: 'Costa Rica', en: 'Costa Rica' },
    CU: { fr: 'Cuba', en: 'Cuba' },
    CV: { fr: 'Cap-Vert', en: 'Cape Verde' },
    CW: { fr: 'Curaçao', en: 'Curaçao' },
    CX: { fr: 'Île Christmas', en: 'Christmas Island' },
    CY: { fr: 'Chypre', en: 'Cyprus' },
    CZ: { fr: 'République Tchèque', en: 'Czech Republic' },
    DE: { fr: 'Allemagne', en: 'Germany' },
    DJ: { fr: 'Djibouti', en: 'Djibouti' },
    DK: { fr: 'Denmark', en: 'Denmark' },
    DM: { fr: 'Dominique', en: 'Dominica' },
    DO: { fr: 'République Dominicaine', en: 'Dominican Republic' },
    DZ: { fr: 'Algérie', en: 'Algeria' },
    EC: { fr: 'Équateur', en: 'Ecuador' },
    EE: { fr: 'Estonie', en: 'Estonia' },
    EG: { fr: 'Égypte', en: 'Egypt' },
    EH: { fr: 'Sahara Occidental', en: 'Western Sahara' },
    ER: { fr: 'Érythrée', en: 'Eritrea' },
    ES: { fr: 'Espagne', en: 'Spain' },
    ET: { fr: 'Éthiopie', en: 'Ethiopia' },
    EU: { fr: 'Europe', en: 'Europe' },
    FI: { fr: 'Finlande', en: 'Finland' },
    FJ: { fr: 'Fidji', en: 'Fiji' },
    FK: { fr: 'Îles Malouines', en: 'Falkland Islands' },
    FM: { fr: 'États Fédérés De Micronésie', en: 'Federated States of Micronesia' },
    FO: { fr: 'Îles Féroé', en: 'Faroe Islands' },
    FR: { fr: 'France', en: 'France' },
    GA: { fr: 'Gabon', en: 'Gabon' },
    GB: { fr: 'Royaume-Uni', en: 'United Kingdom' },
    GD: { fr: 'Grenade', en: 'Grenada' },
    GE: { fr: 'Géorgie', en: 'Georgia' },
    GF: { fr: 'Guyane', en: 'French Guiana' },
    GG: { fr: 'Guernesey', en: 'Guernsey' },
    GH: { fr: 'Ghana', en: 'Ghana' },
    GI: { fr: 'Gibraltar', en: 'Gibraltar' },
    GL: { fr: 'Groenland', en: 'Greenland' },
    GM: { fr: 'Gambie', en: 'Gambia' },
    GN: { fr: 'Guinée', en: 'Guinea' },
    GP: { fr: 'Guadeloupe', en: 'Guadeloupe' },
    GQ: { fr: 'Guinée Équatoriale', en: 'Equatorial Guinea' },
    GR: { fr: 'Grèce', en: 'Greece' },
    GS: {
        fr: 'Géorgie Du Sud-Et-Les Îles Sandwich Du Sud',
        en: 'South Georgia and the South Sandwich Islands',
    },
    GT: { fr: 'Guatemala', en: 'Guatemala' },
    GU: { fr: 'Guam', en: 'Guam' },
    GW: { fr: 'Guinée-Bissau', en: 'Guinea-Bissau' },
    GY: { fr: 'Guyana', en: 'Guyana' },
    HK: { fr: 'Hong Kong', en: 'Hong Kong' },
    HM: { fr: 'Îles Heard-Et-MacDonald', en: 'Heard Island and McDonald Islands' },
    HN: { fr: 'Honduras', en: 'Honduras' },
    HR: { fr: 'Croatie', en: 'Croatia' },
    HT: { fr: 'Haïti', en: 'Haiti' },
    HU: { fr: 'Hongrie', en: 'Hungary' },
    ID: { fr: 'Indonésie', en: 'Indonesia' },
    IE: { fr: 'Irlande', en: 'Ireland' },
    IL: { fr: 'Israël', en: 'Israel' },
    IM: { fr: 'Île De Man', en: 'Isle of Man' },
    IN: { fr: 'Inde', en: 'India' },
    IO: { fr: "Territoire Britannique De L'océan Indien", en: 'British Indian Ocean Territory' },
    IQ: { fr: 'Irak', en: 'Iraq' },
    IR: { fr: "République Islamique D'Iran", en: 'Islamic Republic of Iran' },
    IS: { fr: 'Islande', en: 'Iceland' },
    IT: { fr: 'Italie', en: 'Italy' },
    JE: { fr: 'Jersey', en: 'Jersey' },
    JM: { fr: 'Jamaïque', en: 'Jamaica' },
    JO: { fr: 'Jordanie', en: 'Jordan' },
    JP: { fr: 'Japon', en: 'Japan' },
    KE: { fr: 'Kenya', en: 'Kenya' },
    KG: { fr: 'Kirghizistan', en: 'Kyrgyzstan' },
    KH: { fr: 'Cambodge', en: 'Cambodia' },
    KI: { fr: 'Kiribati', en: 'Kiribati' },
    KM: { fr: 'Comores', en: 'Comoros' },
    KN: { fr: 'Saint-Christophe-et-Niévès', en: 'Saint Kitts and Nevis' },
    KP: {
        fr: 'République Populaire Démocratique De Corée',
        en: "Democratic People's Republic of Korea",
    },
    KR: { fr: 'République De Corée', en: 'Republic of Korea' },
    KW: { fr: 'Koweït', en: 'Kuwait' },
    KY: { fr: 'Îles Caïmans', en: 'Cayman Islands' },
    KZ: { fr: 'Kazakhstan', en: 'Kazakhstan' },
    LA: { fr: 'République Démocratique Populaire Lao', en: "Lao People's Democratic Republic" },
    LB: { fr: 'Liban', en: 'Lebanon' },
    LC: { fr: 'Sainte-Lucie', en: 'Saint Lucia' },
    LI: { fr: 'Liechtenstein', en: 'Liechtenstein' },
    LK: { fr: 'Sri Lanka', en: 'Sri Lanka' },
    LR: { fr: 'Liberia', en: 'Liberia' },
    LS: { fr: 'Lesotho', en: 'Lesotho' },
    LT: { fr: 'Lituanie', en: 'Lithuania' },
    LU: { fr: 'Luxembourg', en: 'Luxembourg' },
    LV: { fr: 'Lettonie', en: 'Latvia' },
    LY: { fr: 'Libye', en: 'Libya' },
    MA: { fr: 'Maroc', en: 'Morocco' },
    MC: { fr: 'Monaco', en: 'Monaco' },
    MD: { fr: 'République De Moldavie', en: 'Republic of Moldova' },
    ME: { fr: 'Monténégro', en: 'Montenegro' },
    MF: { fr: 'Saint-Martin (Partie Française)', en: 'Saint Martin (French Part)' },
    MG: { fr: 'Madagascar', en: 'Madagascar' },
    MH: { fr: 'Îles Marshall', en: 'Marshall Islands' },
    MK: { fr: 'Macédoine', en: 'North Macedonia' },
    ML: { fr: 'Mali', en: 'Mali' },
    MM: { fr: 'Birmanie', en: 'Myanmar' },
    MN: { fr: 'Mongolie', en: 'Mongolia' },
    MO: { fr: 'Macao', en: 'Macao' },
    MP: { fr: 'Îles Mariannes Du Nord', en: 'Northern Mariana Islands' },
    MQ: { fr: 'Martinique', en: 'Martinique' },
    MR: { fr: 'Mauritanie', en: 'Mauritania' },
    MS: { fr: 'Montserrat', en: 'Montserrat' },
    MT: { fr: 'Malte', en: 'Malta' },
    MU: { fr: 'Maurice', en: 'Mauritius' },
    MV: { fr: 'Maldives', en: 'Maldives' },
    MW: { fr: 'Malawi', en: 'Malawi' },
    MX: { fr: 'Mexique', en: 'Mexico' },
    MY: { fr: 'Malaisie', en: 'Malaysia' },
    MZ: { fr: 'Mozambique', en: 'Mozambique' },
    NA: { fr: 'Namibie', en: 'Namibia' },
    NC: { fr: 'Nouvelle-Calédonie', en: 'New Caledonia' },
    NE: { fr: 'Niger', en: 'Niger' },
    NF: { fr: 'Île Norfolk', en: 'Norfolk Island' },
    NG: { fr: 'Nigéria', en: 'Nigeria' },
    NI: { fr: 'Nicaragua', en: 'Nicaragua' },
    NL: { fr: 'Pays-Bas', en: 'Netherlands' },
    NO: { fr: 'Norvège', en: 'Norway' },
    NP: { fr: 'Népal', en: 'Nepal' },
    NR: { fr: 'Nauru', en: 'Nauru' },
    NU: { fr: 'Niue', en: 'Niue' },
    NZ: { fr: 'Nouvelle-Zélande', en: 'New Zealand' },
    OM: { fr: 'Oman', en: 'Oman' },
    PA: { fr: 'Panama', en: 'Panama' },
    PE: { fr: 'Pérou', en: 'Peru' },
    PF: { fr: 'Polynésie Française', en: 'French Polynesia' },
    PG: { fr: 'Papouasie-Nouvelle-Guinée', en: 'Papua New Guinea' },
    PH: { fr: 'Philippines', en: 'Philippines' },
    PK: { fr: 'Pakistan', en: 'Pakistan' },
    PL: { fr: 'Pologne', en: 'Poland' },
    PM: { fr: 'Saint-Pierre-Et-Miquelon', en: 'Saint Pierre and Miquelon' },
    PN: { fr: 'Pitcairn', en: 'Pitcairn' },
    PR: { fr: 'Porto Rico', en: 'Puerto Rico' },
    PS: { fr: 'Territoires Palestiniens Occupés', en: 'Palestinian Territory' },
    PT: { fr: 'Portugal', en: 'Portugal' },
    PW: { fr: 'Palaos', en: 'Palau' },
    PY: { fr: 'Paraguay', en: 'Paraguay' },
    QA: { fr: 'Qatar', en: 'Qatar' },
    RE: { fr: 'Réunion', en: 'Réunion' },
    RO: { fr: 'Roumanie', en: 'Romania' },
    RS: { fr: 'Serbie', en: 'Serbia' },
    RU: { fr: 'Fédération De Russie', en: 'Russian Federation' },
    RW: { fr: 'Rwanda', en: 'Rwanda' },
    SA: { fr: 'Arabie Saoudite', en: 'Saudi Arabia' },
    SB: { fr: 'Îles Salomon', en: 'Solomon Islands' },
    SC: { fr: 'Seychelles', en: 'Seychelles' },
    SD: { fr: 'Soudan', en: 'Sudan' },
    SE: { fr: 'Suède', en: 'Sweden' },
    SG: { fr: 'Singapour', en: 'Singapore' },
    SH: { fr: 'Sainte-Hélène', en: 'Saint Helena' },
    SI: { fr: 'Slovénie', en: 'Slovenia' },
    SJ: { fr: 'Svalbard Et Jan Mayen', en: 'Svalbard and Jan Mayen' },
    SK: { fr: 'Slovaquie', en: 'Slovakia' },
    SL: { fr: 'Sierra Leone', en: 'Sierra Leone' },
    SM: { fr: 'Saint-Marin', en: 'San Marino' },
    SN: { fr: 'Sénégal', en: 'Senegal' },
    SO: { fr: 'Somalie', en: 'Somalia' },
    SR: { fr: 'Suriname', en: 'Suriname' },
    SS: { fr: 'Soudan Du Sud', en: 'South Sudan' },
    ST: { fr: 'Sao Tomé-Et-Principe', en: 'Sao Tome and Principe' },
    SV: { fr: 'République Du Salvador', en: 'El Salvador' },
    SX: { fr: 'Saint-Martin (Partie Néerlandaise)', en: 'Sint Maarten (Dutch Part)' },
    SY: { fr: 'République Arabe Syrienne', en: 'Syrian Arab Republic' },
    SZ: { fr: 'Swaziland', en: 'Eswatini' },
    TC: { fr: 'Îles Turks-Et-Caïcos', en: 'Turks and Caicos Islands' },
    TD: { fr: 'Tchad', en: 'Chad' },
    TF: { fr: 'Terres Australes Françaises', en: 'French Southern Territories' },
    TG: { fr: 'Togo', en: 'Togo' },
    TH: { fr: 'Thaïlande', en: 'Thailand' },
    TJ: { fr: 'Tadjikistan', en: 'Tajikistan' },
    TK: { fr: 'Tokelau', en: 'Tokelau' },
    TL: { fr: 'Timor-Leste', en: 'Timor-Leste' },
    TM: { fr: 'Turkménistan', en: 'Turkmenistan' },
    TN: { fr: 'Tunisie', en: 'Tunisia' },
    TO: { fr: 'Tonga', en: 'Tonga' },
    TR: { fr: 'Turquie', en: 'Turkey' },
    TT: { fr: 'Trinité-Et-Tobago', en: 'Trinidad and Tobago' },
    TV: { fr: 'Tuvalu', en: 'Tuvalu' },
    TW: { fr: 'Taïwan', en: 'Taiwan' },
    TZ: { fr: 'République-Unie De Tanzanie', en: 'United Republic of Tanzania' },
    UA: { fr: 'Ukraine', en: 'Ukraine' },
    UG: { fr: 'Ouganda', en: 'Uganda' },
    UM: {
        fr: 'Îles Mineures Éloignées Des États-Unis',
        en: 'United States Minor Outlying Islands',
    },
    US: { fr: 'États-Unis', en: 'United States' },
    UY: { fr: 'Uruguay', en: 'Uruguay' },
    UZ: { fr: 'Ouzbékistan', en: 'Uzbekistan' },
    VA: { fr: 'Saint-Siège (État De La Cité Du Vatican)', en: 'Holy See (Vatican City State)' },
    VC: { fr: 'Saint-Vincent-Et-Les Grenadines', en: 'Saint Vincent and the Grenadines' },
    VE: { fr: 'Venezuela', en: 'Venezuela' },
    VG: { fr: 'Îles Vierges Britanniques', en: 'British Virgin Islands' },
    VI: { fr: 'Îles Vierges Des États-Unis', en: 'U.S. Virgin Islands' },
    VN: { fr: 'Viet Nam', en: 'Vietnam' },
    VU: { fr: 'Vanuatu', en: 'Vanuatu' },
    WF: { fr: 'Wallis Et Futuna', en: 'Wallis and Futuna' },
    WS: { fr: 'Samoa', en: 'Samoa' },
    YE: { fr: 'Yémen', en: 'Yemen' },
    YT: { fr: 'Mayotte', en: 'Mayotte' },
    ZA: { fr: 'Afrique Du Sud', en: 'South Africa' },
    ZM: { fr: 'Zambie', en: 'Zambia' },
    ZW: { fr: 'Zimbabwe', en: 'Zimbabwe' },
} as const;

export const COUNTRY_CODES = Object.keys(COUNTRIES) as Array<keyof typeof COUNTRIES>;
