name: Continuous Integration Pipeline

on:
  push:
    branches:
      - 'main'

jobs:
  scan-code:
    name: Scan code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run linter
        run: yarn lint

      - name: Run data checks
        run: yarn check-data
